// Curated subset of DHIS2 authorities. Not a Zod enum — callers may pass any
// string (app-module or custom authorities are valid server-side).
export const Authority = {
  ALL: 'ALL',

  F_DATAVALUE_ADD: 'F_DATAVALUE_ADD',
  F_EXPORT_DATA: 'F_EXPORT_DATA',
  F_SKIP_DATA_IMPORT_AUDIT: 'F_SKIP_DATA_IMPORT_AUDIT',
  F_APPROVE_DATA: 'F_APPROVE_DATA',
  F_APPROVE_DATA_LOWER_LEVELS: 'F_APPROVE_DATA_LOWER_LEVELS',
  F_ACCEPT_DATA_LOWER_LEVELS: 'F_ACCEPT_DATA_LOWER_LEVELS',
  F_VIEW_UNAPPROVED_DATA: 'F_VIEW_UNAPPROVED_DATA',
  F_RUN_VALIDATION: 'F_RUN_VALIDATION',
  F_PREDICTOR_RUN: 'F_PREDICTOR_RUN',
  F_GENERATE_MIN_MAX_VALUES: 'F_GENERATE_MIN_MAX_VALUES',
  F_MINMAX_DATAELEMENT_ADD: 'F_MINMAX_DATAELEMENT_ADD',
  F_EDIT_EXPIRED: 'F_EDIT_EXPIRED',
  F_UNCOMPLETE_EVENT: 'F_UNCOMPLETE_EVENT',

  F_METADATA_EXPORT: 'F_METADATA_EXPORT',
  F_METADATA_IMPORT: 'F_METADATA_IMPORT',
  F_METADATA_MANAGE: 'F_METADATA_MANAGE',
  F_PERFORM_MAINTENANCE: 'F_PERFORM_MAINTENANCE',
  F_SYSTEM_SETTING: 'F_SYSTEM_SETTING',
  F_VIEW_SERVER_INFO: 'F_VIEW_SERVER_INFO',

  F_USER_VIEW: 'F_USER_VIEW',
  F_REPLICATE_USER: 'F_REPLICATE_USER',

  F_VIEW_EVENT_ANALYTICS: 'F_VIEW_EVENT_ANALYTICS',
  F_PERFORM_ANALYTICS_EXPLAIN: 'F_PERFORM_ANALYTICS_EXPLAIN',

  F_TRACKED_ENTITY_INSTANCE_ADD: 'F_TRACKED_ENTITY_INSTANCE_ADD',
  F_TRACKED_ENTITY_INSTANCE_SEARCH: 'F_TRACKED_ENTITY_INSTANCE_SEARCH',
  F_TRACKED_ENTITY_INSTANCE_LIST: 'F_TRACKED_ENTITY_INSTANCE_LIST',
  F_ENROLLMENT_CASCADE_DELETE: 'F_ENROLLMENT_CASCADE_DELETE',
  F_TRACKED_ENTITY_MERGE: 'F_TRACKED_ENTITY_MERGE',
  F_PROGRAM_ENROLLMENT: 'F_PROGRAM_ENROLLMENT',
  F_PROGRAM_UNENROLLMENT: 'F_PROGRAM_UNENROLLMENT',
  F_PROGRAM_STAGE_INSTANCE_ADD: 'F_PROGRAM_STAGE_INSTANCE_ADD',
  F_PROGRAM_STAGE_INSTANCE_DELETE: 'F_PROGRAM_STAGE_INSTANCE_DELETE',
  F_PROGRAM_STAGE_INSTANCE_SEARCH: 'F_PROGRAM_STAGE_INSTANCE_SEARCH',
  F_EXPORT_EVENTS: 'F_EXPORT_EVENTS',
} as const

export type Authority = (typeof Authority)[keyof typeof Authority]
